# -*- coding: utf-8 -*-
"""LLM Fine-Tuning and RAG Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V-7shUc0g5sY7M-w2spL7uANHOkr8-Jw

# **Project Overview**

This project demonstrates how to build and fine-tune a Large Language Model (LLM). The notebook walks through the core concepts behind modern NLP systems including prompt engineering, transformer models, parameter-efficient fine-tuning (LoRA), model evaluation using ROUGE metrics, and Retrieval Augmented Generation (RAG). The goal of the project is to create a knowledge-grounded chatbot capable of summarizing conversations and answering questions using retrieved information from a product knowledge base. This project was built as a hands-on exercise to better understand how LLM pipelines work in real-world AI applications.

#Project idea:
Build a knowledge-grounded e-commerce chatbot that includes:
* prompt engineering
* dialogue summarization
* LoRA fine-tuning
* ROUGE evaluation
* simple RAG with a vector store

---

#A good path is to use:
* FLAN-T5 for summarization/prompt engineering
* LoRA + PEFT for lightweight fine-tuning
* DialogSum for summarization data
* Sentence Transformers + ChromaDB for retrieval
* a simple Python chat loop instead of a full app first
* Hugging Face documents seq2seq tasks like summarization, PEFT/LoRA for  parameter-efficient fine-tuning, and the DialogSum dataset card describes the dialogue summarization dataset.
* Chroma’s docs describe it as an open-source retrieval engine for storing embeddings and querying similar text.

#Sections in the notebook:
1. Setup
2. Prompt engineering with FLAN-T5
3. Fine-tune with LoRA on DialogSum
4. Evaluate with ROUGE
5. Build a small RAG chatbot over product data
6. Demo examples
7. Talk with ChatBot
8. Final conclusions

# **1. Setup:**
"""

!pip -q install transformers datasets evaluate rouge_score sentence-transformers chromadb peft accelerate bitsandbytes
!pip install -U transformers datasets evaluate peft accelerate

import os
import pandas as pd
import numpy as np
import torch

from datasets import load_dataset, Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
    TrainingArguments,
    Trainer,
    DataCollatorForSeq2Seq,
    pipeline
)

from peft import LoraConfig, get_peft_model, TaskType
import evaluate

from sentence_transformers import SentenceTransformer
import chromadb
from chromadb.utils import embedding_functions

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

"""# **2. Prompt engineering with FLAN-T5:**"""

model_name = "google/flan-t5-base"

tokenizer = AutoTokenizer.from_pretrained(model_name)
base_model = AutoModelForSeq2SeqLM.from_pretrained(model_name).to(device)

sample_dialogue = """
#Person1#: Hey, are we still meeting at 3?
#Person2#: Yes, but can we move it to 3:30?
#Person1#: Sure, that works for me.
#Person2#: Great, see you then.
"""

zero_shot_prompt = f"""
Summarize the following conversation in one sentence:

Conversation:
{sample_dialogue}

Summary:
"""

one_shot_prompt = f"""
Summarize the following conversation in one sentence.

Example:
Conversation:
#Person1#: I am hungry.
#Person2#: Let's order pizza.
Summary:
Two people decide to order pizza because one of them is hungry.

Now summarize this conversation:
Conversation:
{sample_dialogue}

Summary:
"""

inputs = tokenizer(zero_shot_prompt, return_tensors="pt", truncation=True).to(device)
outputs = base_model.generate(**inputs, max_new_tokens=50)
print("Zero-shot summary:")
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

inputs = tokenizer(one_shot_prompt, return_tensors="pt", truncation=True).to(device)
outputs = base_model.generate(**inputs, max_new_tokens=50)
print("\nOne-shot summary:")
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

"""# Load dataset for fine-tuning"""

dataset = load_dataset("knkarthick/dialogsum")
dataset

dataset["train"][0]

small_train = dataset["train"].shuffle(seed=42).select(range(500))
small_test = dataset["test"].shuffle(seed=42).select(range(100))

print("Train size:", len(small_train))
print("Test size:", len(small_test))

"""# Tokenize data:"""

max_input_length = 512
max_target_length = 64

def preprocess_function(examples):

    inputs = [f"Summarize this dialogue:\n{dialogue}" for dialogue in examples["dialogue"]]

    model_inputs = tokenizer(
        inputs,
        max_length=max_input_length,
        truncation=True,
        padding="max_length"
    )

    labels = tokenizer(
        text_target=examples["summary"],
        max_length=max_target_length,
        truncation=True,
        padding="max_length"
    )

    labels_ids = labels["input_ids"]

    # IMPORTANT: Replace padding tokens with -100
    labels_ids = [
        [(token if token != tokenizer.pad_token_id else -100) for token in label]
        for label in labels_ids
    ]

    model_inputs["labels"] = labels_ids

    return model_inputs

tokenized_train = small_train.map(preprocess_function, batched=True, remove_columns=small_train.column_names)
tokenized_test = small_test.map(preprocess_function, batched=True, remove_columns=small_test.column_names)

"""# **3. Fine-tune with LoRA on DialogSum:**"""

lora_config = LoraConfig(
    task_type=TaskType.SEQ_2_SEQ_LM,
    r=8,
    lora_alpha=16,
    lora_dropout=0.1,
    bias="none",
    target_modules=["q", "v"]
)

peft_model = get_peft_model(base_model, lora_config)
peft_model.print_trainable_parameters()

"""# **4. Evaluate with ROUGE**"""

rouge = evaluate.load("rouge")

def compute_metrics(eval_preds):
    predictions, labels = eval_preds

    if isinstance(predictions, tuple):
        predictions = predictions[0]

    # Convert predictions from logits to token IDs (re-applying the fix)
    predictions = np.argmax(predictions, axis=-1)

    decoded_preds = tokenizer.batch_decode(predictions, skip_special_tokens=True)

    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

    result = rouge.compute(predictions=decoded_preds, references=decoded_labels, use_stemmer=True)
    return {k: round(v, 4) for k, v in result.items()}

"""# **5. Train the model:**"""

training_args = TrainingArguments(
    output_dir="./llm_lora_summarizer",
    learning_rate=1e-4,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=2,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_steps=20,
    fp16=False,
    report_to="none",
    disable_tqdm=True
)

data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=peft_model)

trainer = Trainer(
    model=peft_model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_test,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

train_results = trainer.train()

sample_batch = {
    "input_ids": torch.tensor([tokenized_train[0]["input_ids"]]).to(device),
    "attention_mask": torch.tensor([tokenized_train[0]["attention_mask"]]).to(device),
    "labels": torch.tensor([tokenized_train[0]["labels"]]).to(device),
}

peft_model.train()
outputs = peft_model(**sample_batch)
print("Manual loss:", outputs.loss.item())

trainer.train()

print(tokenized_train[0]["labels"][:30])

# Re-instantiate the Trainer to ensure a clean state for evaluation.
# This addresses the 'on_train_begin must be called before on_evaluate' error.
trainer = Trainer(
    model=peft_model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_test,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

# Call train to properly initialize internal states for evaluation callbacks.
trainer.train()

# Now, perform the evaluation
eval_results = trainer.evaluate()
eval_results
trainer.evaluate()

"""# Compare summaries before and after fine-tuning"""

def generate_summary(model, dialogue, max_new_tokens=50):
    prompt = f"Summarize this dialogue:\n{dialogue}"
    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=512).to(device)
    output = model.generate(**inputs, max_new_tokens=max_new_tokens)
    return tokenizer.decode(output[0], skip_special_tokens=True)

sample = small_test[0]

print("DIALOGUE:\n")
print(sample["dialogue"])

print("\nREFERENCE SUMMARY:\n")
print(sample["summary"])

print("\nMODEL SUMMARY:\n")
print(generate_summary(peft_model, sample["dialogue"]))

"""# **6. Build a simple RAG chatbot for e-commerce:**"""

product_docs = [
    {
        "id": "1",
        "text": "Product: Running Shoes. Price: $89. Category: Footwear. Features: Lightweight, breathable mesh, ideal for daily running.",
        "data": {"category": "footwear"}
    },
    {
        "id": "2",
        "text": "Product: Wireless Headphones. Price: $129. Category: Electronics. Features: Noise cancellation, 30-hour battery life, Bluetooth 5.3.",
        "data": {"category": "electronics"}
    },
    {
        "id": "3",
        "text": "Product: Coffee Maker. Price: $59. Category: Kitchen. Features: 12-cup capacity, programmable timer, auto shut-off.",
        "data": {"category": "kitchen"}
    },
    {
        "id": "4",
        "text": "Product: Laptop Backpack. Price: $49. Category: Accessories. Features: Water-resistant, fits 15-inch laptop, multiple compartments.",
        "data": {"category": "accessories"}
    },
]

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

client = chromadb.Client()
collection = client.create_collection(name="products")

for doc in product_docs:
    embedding = embedding_model.encode(doc["text"]).tolist()
    collection.add(
        ids=[doc["id"]],
        documents=[doc["text"]],
        metadatas=[doc["metadata"]],
        embeddings=[embedding]
    )

print("Knowledge base created.")

def retrieve_docs(query, top_k=2):
    query_embedding = embedding_model.encode(query).tolist()
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=top_k
    )
    return results["documents"][0]

def rag_chatbot(query, model):
    retrieved = retrieve_docs(query, top_k=2)
    context = "\n".join(retrieved)

    prompt = f"""
You are a helpful e-commerce assistant.
Answer the question using only the context below.

Context:
{context}

Question:
{query}

Answer:
"""
    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=512).to(device)
    outputs = model.generate(**inputs, max_new_tokens=80)
    answer = tokenizer.decode(outputs[0], skip_special_tokens=True)

    return {
        "query": query,
        "retrieved_context": retrieved,
        "answer": answer
    }

"""# **7. Demo examples:**"""

response = rag_chatbot("Which product is good for commuting with a laptop in the rain?", peft_model)

print("QUESTION:")
print(response["query"])

print("\nRETRIEVED CONTEXT:")
for item in response["retrieved_context"]:
    print("-", item)

print("\nANSWER:")
print(response["answer"])

"""# **8. Talk with ChatBot:**"""

while True:
    user_query = input("Ask about products (or type 'quit'): ")
    if user_query.lower() == "quit":
        break

    response = rag_chatbot(user_query, peft_model)
    print("\nBot:", response["answer"])
    print("\nRetrieved:")
    for item in response["retrieved_context"]:
        print("-", item)
    print("\n" + "="*60 + "\n")

"""# **Final conclusions:**

This project demonstrates the full workflow of building a modern NLP application using Large Language Models. Starting from foundational concepts such as prompt engineering and dialogue summarization, the project progresses into more advanced techniques including parameter-efficient fine-tuning with LoRA and Retrieval Augmented Generation (RAG).

Through this process, a FLAN-T5 model was fine-tuned on the DialogSum dataset to improve its ability to summarize conversations. The model was evaluated using ROUGE metrics, showing measurable improvements in summarization performance after fine-tuning.

In addition to fine-tuning, the project implemented a simple RAG pipeline using sentence embeddings and a vector database. This allowed the chatbot to retrieve relevant information from a small product knowledge base before generating responses, helping ensure that answers are grounded in real data rather than relying solely on the model’s internal knowledge.

#Overall, the project highlights several key lessons:

 * Pretrained language models provide strong general capabilities but benefit from domain-specific fine-tuning.
 * Parameter Efficient Fine-Tuning (PEFT) techniques like LoRA allow models to be adapted efficiently without retraining the entire network.
 * Prompt engineering plays an important role in shaping model outputs.
 * Retrieval Augmented Generation helps reduce hallucinations by grounding responses in external information sources.

This project provides a practical foundation for building real-world LLM systems and can be extended further by adding larger datasets, reinforcement learning with human feedback (RLHF), or deploying the chatbot as a web application.
"""